# Generated by Django 5.2.12 on 2026-04-16 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_service_image_alter_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vendor',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='neelaiah', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=23, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
