# Generated by Django 5.2.12 on 2026-04-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_booking_vendor_booking_name_booking_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='user_name',
        ),
    ]
