# Generated by Django 5.2.12 on 2026-04-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_name_booking_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_name',
            new_name='name',
        ),
    ]
