# Generated by Django 5.2.12 on 2026-04-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
