# Generated by Django 5.2.12 on 2026-04-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_booking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='order_id',
        ),
    ]
