# Generated by Django 5.2.12 on 2026-04-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_booking_id_booking_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
