# Generated by Django 5.2.12 on 2026-04-17 05:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_booking_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_id',
            field=models.CharField(default=accounts.models.generate_order_id, editable=False, max_length=20, unique=True),
        ),
    ]
