# Generated by Django 5.2.12 on 2026-04-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_bookinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
