# Generated by Django 5.2.12 on 2026-04-21 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_bookinghistory_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.CharField(default=datetime.date.today, max_length=50),
            preserve_default=False,
        ),
    ]
