# Generated by Django 5.2.12 on 2026-04-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='screenshot',
            new_name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='transaction_id',
        ),
    ]
