# Generated by Django 5.2.12 on 2026-04-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_screenshot_payment_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
