# Generated by Django 5.2.12 on 2026-04-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_screenshot',
            new_name='screenshot',
        ),
    ]
