# Generated by Django 6.0.4 on 2026-05-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_privacypolicy"),
        ("accounts", "0019_payment_due_date_payment_payment_request_and_more"),
    ]

    operations = []
