# Generated by Django 5.2.12 on 2026-04-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_payment_screenshot_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='accounts.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.category'),
            preserve_default=False,
        ),
    ]
