# Generated by Django 5.2.12 on 2026-04-24 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_payment_service'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('locality', models.CharField(db_index=True, max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(db_index=True, max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profiles', to='core.category')),
                ('services', models.ManyToManyField(blank=True, related_name='vendor_profiles', to='core.categoryservice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
